import {db,runtime} from './server';
const enc=new TextEncoder();
function b64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes));}
function bytes(value:string){return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
async function key(){if(!runtime.X_TOKEN_SECRET)throw new Error('X 连接尚未配置');const digest=await crypto.subtle.digest('SHA-256',enc.encode(runtime.X_TOKEN_SECRET));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),enc.encode(JSON.stringify(value)));return b64(iv)+'.'+b64(new Uint8Array(data));}
export async function unseal<T>(value:string):Promise<T>{const [iv,data]=value.split('.');return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(iv)},await key(),bytes(data))));}
export function random(){return b64(crypto.getRandomValues(new Uint8Array(32))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');}
export async function hash(value:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');}
export async function tokenRequest(params:URLSearchParams){const headers:Record<string,string>={'Content-Type':'application/x-www-form-urlencoded'};if(runtime.X_CLIENT_SECRET)headers.Authorization='Basic '+btoa(runtime.X_CLIENT_ID+':'+runtime.X_CLIENT_SECRET);else params.set('client_id',runtime.X_CLIENT_ID||'');const r=await fetch('https://api.x.com/2/oauth2/token',{method:'POST',headers,body:params.toString(),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`X 授权未完成（${r.status}），请重新连接`);return r.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>;}
export async function getXToken(){if(runtime.X_BEARER_TOKEN)return runtime.X_BEARER_TOKEN;const row=await db().prepare("SELECT payload,expires_at FROM connections WHERE id='x-token'").first<{payload:string;expires_at:number}>();if(!row)throw new Error('请先配置 X 接口或完成账号授权');let t=await unseal<{access_token:string;refresh_token?:string}>(row.payload);if(row.expires_at<Date.now()+60000){if(!t.refresh_token)throw new Error('X 授权已过期，请重新连接');const fresh=await tokenRequest(new URLSearchParams({grant_type:'refresh_token',refresh_token:t.refresh_token}));t={...fresh,refresh_token:fresh.refresh_token||t.refresh_token};await db().prepare("UPDATE connections SET payload=?,expires_at=? WHERE id='x-token'").bind(await seal(t),Date.now()+fresh.expires_in*1000).run();}return t.access_token;}
