const dimensions = { audience: '受众与定位', style: '表达风格', structure: '开头与结构', method: '内容方法', operation: '运营线索', comparison: '高低表现对照' };
const metricNames = { bookmarks: '收藏', views: '阅读', likes: '点赞' };
const defaults = ['gkxspace', 'gengdaj', 'khazix0918', 'ai_jasonyu'];
export function initialViralForm() {
  const base = { tab: 'research', handles: [], studyId: '', draftId: '', topic: '', ownAngle: '', ownMaterial: '', sourceAccount: 'all', sourceQuery: '', sources: [], styleHandle: 'all', bodies: {}, imagePlans: {} };
  try { return { ...base, ...JSON.parse(localStorage.getItem('radar-viral-form') || '{}') }; }
  catch { return base; }
}
export function persistViralForm(form) { try { localStorage.setItem('radar-viral-form', JSON.stringify(form)); } catch { /* Server records remain available if browser storage is full. */ } }
export function initializeViralForm(state, form) {
  if (!form.initialized) { form.handles = state.x.config.accounts.filter(a => defaults.includes(a.handle.toLowerCase())).map(a => a.handle); form.initialized = true; }
  if (!state.viral?.studies.some(s => s.id === form.studyId)) form.studyId = state.viral?.studies[0]?.id || '';
  if (!state.viral?.drafts.some(s => s.id === form.draftId)) form.draftId = state.viral?.drafts[0]?.id || '';
  form.handles = form.handles.filter(h => state.x.config.accounts.some(a => a.handle === h));
}
export function viralImageWorkbench(draft, state, form, ui) {
  const { esc: e, button: b, notice } = ui;
  const plans = form.imagePlans?.[draft.id] || draft.images;
  const current = draft.images.map((_, n) => draft.imageAssets?.find(a => a.current && a.imageIndex === n));
  const completed = current.filter(Boolean).length, api = state.settings?.imageMode === 'api';
  const stale = draft.imagePromptsCurrent === false || (form.bodies[draft.id] ?? draft.body) !== draft.body;
  const changed = JSON.stringify(plans) !== JSON.stringify(draft.images);
  const history = (draft.imageAssets || []).filter(a => !current.some(c => c?.id === a.id));
  return `<div id="viral-image-workbench" class="viral-image-workbench"><div class="sectionhead"><h3>配图制作</h3><span class="pill">${completed}/${draft.images.length} 张已保存</span></div><p class="muted">${api ? `图片 API：${e(state.settings.imageModel)}。点击生成后自动保存，可在这里预览、下载；每次生成可能计费。` : '可以使用 ChatGPT 网页生成后直接导入，也可在「模型与风格」配置图片 API。'}复制提示词和网页生成入口一直保留。</p>${stale ? notice('正文有修改，请先保存正文，再核对并保存配图提示词。旧图片保留在历史记录中。','warn') : ''}${state.settings?.imageCheck?.status === 'failed' ? notice(e(state.settings.imageCheck.message),'warn') : ''}<div class="actions">${api ? b(completed === draft.images.length ? '检查并补齐配图' : completed ? `生成剩余 ${draft.images.length - completed} 张配图` : '一键生成全部配图', 'viral-images', `${stale || changed ? 'disabled' : ''}`, true) : b('配置图片 API','nav','data-view="settings"')}${b('保存并确认配图提示词','viral-save-images')}</div>${changed ? '<p class="muted">提示词有未保存修改，请先保存再生成。</p>' : ''}<div class="viral-picture-grid">${plans.map((image,n) => { const asset = current[n]; return `<article class="viral-picture"><h4>${n + 1}. ${e(image.title)}</h4>${asset ? `<div class="viral-picture-preview"><img src="/assets/${e(asset.file)}" alt="${e(asset.label)}"><div class="actions"><a href="/assets/${e(asset.file)}?download=1">下载这张图片</a><a href="/assets/${e(asset.file)}" target="_blank" rel="noopener noreferrer">查看大图</a><small>${asset.origin === 'api' ? `API 已生成 · ${e(asset.model || '图片模型')}` : '已手动导入'}</small></div></div>` : '<div class="viral-picture-placeholder">图片生成或导入后会显示在这里</div>'}<div class="actions">${api ? b(asset ? '重新生成这张图（API）' : '使用 API 生成这张图', 'viral-images', `data-index="${n}" ${asset ? 'data-force="true"' : ''} ${stale || changed ? 'disabled' : ''}`, !asset) : ''}${b('复制这张图的提示词','viral-copy-image',`data-index="${n}"`)}<a href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">打开 ChatGPT 网页 ↗</a></div><details class="viral-image"><summary>查看或修改提示词</summary><label>图片标题<input id="viral-image-title-${n}" data-viral-image-index="${n}" data-viral-image-key="title" value="${e(image.title)}"></label><label>配图提示词<textarea id="viral-image-prompt-${n}" rows="8" data-viral-image-index="${n}" data-viral-image-key="prompt">${e(image.prompt)}</textarea></label></details><details><summary>网页生成后导入，或替换图片</summary><p class="muted">复制提示词 → 在 ChatGPT 网页生成（可用你现有的 Plus）→ 下载 → 选择文件并导入。PNG / JPG / WebP，最多 10MB。</p><input type="file" id="viral-image-file-${n}" accept="image/png,image/jpeg,image/webp" aria-label="第 ${n + 1} 张图片文件">${b('导入这张图片','viral-import-image',`data-index="${n}" ${stale || changed ? 'disabled' : ''}`)}</details></article>`; }).join('')}</div>${history.length ? `<details><summary>历史图片 · ${history.length} 张</summary><p class="muted">下列图片属于旧正文、旧提示词或之前的版本，保留下载，不计入当前配图。</p><div class="gallery">${history.map(a => `<div><img src="/assets/${e(a.file)}" alt="${e(a.label)}"><a href="/assets/${e(a.file)}?download=1">下载历史图：${e(a.label)}</a></div>`).join('')}</div></details>` : ''}<p class="muted">转入「我的稿件」时会带上已保存的配图；确认正文与配图方案后会复用对应图片。</p></div>`;
}
export function viralPage(state, form, ui) {
  const { esc: e, link, date, button: b, notice } = ui;
  const v = state.viral || { studies: [], drafts: [] };
  const study = v.studies.find(s => s.id === form.studyId);
  const draft = v.drafts.find(s => s.id === form.draftId);
  const roots = a => a?.posts?.filter(p => p.own && !p.replyToId && Date.parse(p.publishedAt) >= Date.now() - 12 * 86400000) || [];
  const metric = n => n === null || n === undefined ? '未知' : Number(n).toLocaleString('zh-CN');
  const evidence = (items, report) => `<div class="viral-evidence">${items.map(r => { const s = report.samples.find(s => s.id === r.postId); return `<blockquote>${e(r.quote)}</blockquote><small>${link(s?.url, s ? `${s.authorName} · ${s.role}` : '原帖')} · ${e(date(s?.publishedAt))}</small>`; }).join('')}</div>`;
  const studySelect = (id, label) => `<label>${label}<select id="${id}">${v.studies.length ? v.studies.map(s => `<option value="${s.id}" ${s.id === form.studyId ? 'selected' : ''}>${e(s.authors.map(a => a.name).join('、'))} · ${e(date(s.createdAt))}</option>`).join('') : '<option value="">请先完成一份博主研究</option>'}</select></label>`;
  const header = `<div class="hero"><div><div class="eyebrow">Learn the craft. Find your voice.</div><h1>爆款创作 <span class="x-beta">研究方法 · 原创表达</span></h1><p>拆解 AI 知识型博主的真实内容，把值得借鉴的方法用到你自己的帖子。</p></div></div><div class="viral-tabs">${b('① 研究博主', 'viral-tab', `data-tab="research" data-current="${form.tab === 'research'}"`)}${b('② 写自己的帖子', 'viral-tab', `data-tab="write" data-current="${form.tab === 'write'}"`)}<span>${v.studies.length} 份研究 · ${v.drafts.length} 篇草稿</span></div>`;
  let content;
  if (form.tab !== 'write') {
    const accountCards = state.x.config.accounts.filter(a => a.enabled).sort((a, b) => Number(form.handles.includes(b.handle)) - Number(form.handles.includes(a.handle))).map(a => {
      const snap = state.x.accounts.find(s => s.handle.toLowerCase() === a.handle.toLowerCase()), n = roots(snap).length;
      const selected = form.handles.includes(a.handle);
      return `<label class="viral-account ${selected ? 'selected' : ''}"><input type="checkbox" data-viral-handle="${e(a.handle)}" ${selected ? 'checked' : ''}><span><strong>${e(a.name)}</strong><small>@${e(a.handle)} · ${n} 条近 12 天主帖</small><small>${snap ? '最近取得：' + e(date(snap.fetchedAt)) : '尚未读取'}${snap?.report.status === 'partial' ? ' · 部分取得' : ''}</small></span></label>`;
    }).join('');
    const report = study ? `<section class="panel viral-report"><div class="sectionhead"><h2>博主研究报告</h2><span class="pill">${study.samples.length} 条样本 · 已保存</span></div>${studySelect('viral-study-select', '查看已保存研究')}<p class="muted">样本窗口：${e(date(study.windowStart))}—${e(date(study.windowEnd))}。这份报告保存生成时的样本与指标，刷新信号源后可以重新研究。</p><div class="viral-profile-list">${study.profiles.map((p, n) => {
      const a = study.authors.find(a => a.handle === p.handle);
      return `<details class="viral-profile" ${n === 0 ? 'open' : ''}><summary><strong>${e(p.name)}</strong><span>@${e(p.handle)} · ${a.samples.length} 条样本 · ${a.metric ? '按' + metricNames[a.metric] + '比较' : '指标不足'}</span></summary><p class="muted">已取得 ${a.rootCount} 条近期主帖，其中 ${a.usableCount} 条有足够文字。${a.metric ? `${metricNames[a.metric]}指标可用 ${a.metricAvailable} 条，中间值 ${metric(a.median)}。` : '不标注高低表现。'}采集状态：${a.reportStatus === 'ok' ? '已读取' : '有缺口或状态未知'}。</p>${p.insights.map(i => `<article class="viral-insight"><div class="cardhead"><span class="tag">${dimensions[i.dimension]}</span><small>文本判断把握：${{ high: '高', medium: '中', low: '低' }[i.confidence]}</small></div><h3>${e(i.title)}</h3><p><strong>文字观察：</strong>${e(i.observation)}</p><p class="muted"><strong>机制推断与边界：</strong>${e(i.interpretation)}</p><div class="viral-adapt"><strong>我可以怎样用：</strong>${e(i.adaptation)}</div><details><summary>查看原帖证据</summary>${evidence(i.evidence, study)}</details></article>`).join('')}</details>`;
    }).join('')}</div>${study.comparisons.length ? `<h3>跨博主比较</h3>${study.comparisons.map(c => `<div class="viral-insight"><h3>${e(c.title)}</h3><p>${e(c.observation)}</p><p class="viral-adapt">${e(c.adaptation)}</p><details><summary>查看比较依据</summary>${evidence(c.evidence, study)}</details></div>`).join('')}` : ''}<div class="actions">${b('参考这份研究写帖子 →', 'viral-use-study', '', true)}</div><details><summary>查看 ${study.samples.length} 条样本与原文</summary><div class="viral-sample-grid">${study.samples.map(s => `<article class="viral-sample"><span class="tag">${e(s.role)}</span><h3>${link(s.url, s.title)}</h3><small>${e(s.authorName)} · ${e(date(s.publishedAt))}</small><p class="muted">收藏 ${metric(s.metrics?.bookmarks)} · 阅读 ${metric(s.metrics?.views)} · 点赞 ${metric(s.metrics?.likes)}${s.rank ? ` · 同作者${metricNames[s.metric]}第 ${s.rank} 位` : ''}</p>${s.quoteContext ? `<small>此帖引用 @${e(s.quoteContext.author)}，下面只显示观察作者的文字。</small>` : ''}<details><summary>查看研究使用的作者文字</summary><p class="pre">${e(s.text)}</p><small>${s.textTruncated ? '仅分析正文节选' : '已取得的作者文字'}${s.contentStatus === 'preview_only' ? ' · 长文全文未取得，只使用预览' : ''} · ${e(date(s.fetchedAt))}取得</small></details></article>`).join('')}</div></details><details><summary>研究范围与限制</summary><ul>${study.limitations.map(s => `<li>${e(s)}</li>`).join('')}</ul><p class="muted">使用方法：${e(study.methods.sources.join('、'))}，按 X 图文适配；未运行完整的盲预测或校准流程。</p></details></section>` : `<div class="empty"><h3>先从你关注的四位开始</h3><p>选择博主 → 研究当前样本 → 查看原句依据 → 写自己的帖子。</p><p class="muted">每位至少需要 3 条近期文字主帖。模型研究会使用你已配置的写作服务。</p></div>`;
    content = `<section class="panel"><div class="sectionhead"><h2>选择研究对象</h2><span class="pill">每次 1—4 位</span></div><div class="viral-account-grid">${accountCards}</div><p class="muted">每位选取高位、中间、低位和近期样本，最多 6 条近期文字主帖，另附可取得的置顶参考。默认按收藏比较，指标不足时改用阅读或点赞。</p><div class="actions">${b('研究当前样本', 'viral-research', '', true)}${b('刷新所选博主的公开帖子', 'viral-refresh')}${b('管理 X 观察账号', 'nav', 'data-view="x"')}</div></section>${report}`;
  } else {
    const options = state.x.accounts.flatMap(a => roots(a).map(p => ({ a, p }))).filter(({ a, p }) => (form.sourceAccount === 'all' || a.handle === form.sourceAccount) && (!form.sourceQuery || (p.title + p.body + a.name).toLowerCase().includes(form.sourceQuery.toLowerCase()))).sort((a, b) => b.p.publishedAt.localeCompare(a.p.publishedAt));
    const selected = state.x.accounts.flatMap(a => a.posts.map(p => ({ a, p }))).filter(({ a, p }) => form.sources.some(s => s.handle === a.handle && s.postId === p.id));
    const sourceItem = ({ a, p }) => `<label class="viral-source"><input type="checkbox" data-viral-source="${e(p.id)}" data-handle="${e(a.handle)}" ${form.sources.some(s => s.postId === p.id) ? 'checked' : ''}><span><strong>${e(p.title)}</strong><small>${e(a.name)} · ${e(date(p.publishedAt))} · 收藏 ${metric(p.metrics?.bookmarks)}</small>${link(p.url, '核对原帖 ↗')}</span></label>`;
    const editor = draft ? `<section class="panel viral-draft"><div class="sectionhead"><h2>你的原创参考稿</h2><span class="pill">${[...(form.bodies[draft.id] ?? draft.body)].length} 字符</span></div><label>查看已保存草稿<select id="viral-draft-select">${v.drafts.map(d => `<option value="${d.id}" ${d.id === draft.id ? 'selected' : ''}>${e(d.topic)} · ${e(date(d.createdAt))}</option>`).join('')}</select></label><details><summary>备选标题与提纲</summary><ol>${draft.titles.map(t => `<li>${e(t)}</li>`).join('')}</ol><p class="pre">${e(draft.outline)}</p></details><label>正文 · 可直接修改<textarea id="viral-body" class="editor">${e(form.bodies[draft.id] ?? draft.body)}</textarea></label><p class="muted" id="viral-char-count">${[...(form.bodies[draft.id] ?? draft.body)].length} 字符 · 编辑后先保存。${draft.annotationsEdited ? '来源与方法说明已做编辑校正；再次修改正文后请重新核对。' : draft.edited ? '来源与方法说明来自生成版本，修改后请重新核对。' : ''}</p><div class="actions">${b('保存正文修改', 'viral-save')}${b('复制正文', 'viral-copy')}${b(draft.projectId ? '打开对应稿件 →' : '转入我的稿件，继续配图 →', 'viral-promote', '', true)}</div><div class="divider"></div><h3>借鉴了什么，怎样变成自己的</h3>${draft.methodsUsed.map(m => { const report = v.studies.find(s => s.id === draft.studyId); const i = report?.profiles.flatMap(p => p.insights).find(i => i.id === m.insightId); return `<p><strong>${e(i?.title || m.insightId)}：</strong>${e(m.application)}</p>`; }).join('')}<details><summary>事实依据与待核实事项</summary>${draft.sourceNotes.map(n => { const m = draft.materials.find(m => m.id === n.materialId); return `<p><strong>${e(n.use)}</strong></p><blockquote>${e(n.quote)}</blockquote><small>${m.url ? link(m.url, m.name) : e(m.name)} · 尚需核实</small>`; }).join('')}<ul>${draft.verificationNotes.map(n => `<li>${e(n)}</li>`).join('')}</ul></details>${draft.overlaps.length ? notice('生成稿与参考样本存在较长的文字重合，请核对并改写：' + draft.overlaps.map(o => `<blockquote>${e(o.quote)}</blockquote>`).join(''), 'warn') : '<p class="muted">已检查明显的长句重合；此检查不能证明原创或识别 AI 作者。</p>'}${viralImageWorkbench(draft, state, form, ui)}</section>` : `<div class="empty"><h3>用自己的角度，写第一篇参考稿。</h3><p>至少选一份真实材料，或补充 100 字以上的原文、观察或经历，再生成正文。</p></div>`;
    content = `<section class="panel"><h2>确定主题与自己的角度</h2>${studySelect('viral-write-study', '借鉴哪份研究')}${study ? `<label>参考谁的方法<select id="viral-style-handle"><option value="all">综合所选博主的通用方法</option>${study.profiles.map(p => `<option value="${e(p.handle)}" ${form.styleHandle === p.handle ? 'selected' : ''}>${e(p.name)}</option>`).join('')}</select></label>` : ''}<label>这篇想讲什么<input id="viral-topic" value="${e(form.topic)}" placeholder="例如：普通人如何判断一个 AI 工具值得尝试"></label><label>你自己的角度、判断或希望读者做到的事<textarea id="viral-angle" rows="3" placeholder="讲清我想补充的视角；没有亲测就明确写资料整理。">${e(form.ownAngle)}</textarea></label><label>补充事实材料或你自己的经历（选填；没有 X 材料时至少 100 字）<textarea id="viral-material" rows="5" placeholder="粘贴原文、来源说明、实际观察与限制。不要填没有发生的个人经历。">${e(form.ownMaterial)}</textarea></label><details class="viral-material-picker" ${form.sources.length ? '' : 'open'}><summary>选择这篇帖子的事实材料 · 已选 ${form.sources.length}/4</summary><p class="muted">研究报告用于借鉴方法，下面的材料用于正文事实。选帖只表示取得材料，关键事实仍需核对。</p><div class="viral-source-filters"><select id="viral-source-account"><option value="all">全部观察账号</option>${state.x.config.accounts.map(a => `<option value="${e(a.handle)}" ${form.sourceAccount === a.handle ? 'selected' : ''}>${e(a.name)}</option>`).join('')}</select><input id="viral-source-query" value="${e(form.sourceQuery)}" placeholder="搜索材料标题或文字"></div>${selected.length ? `<div class="viral-selected-sources">${selected.map(sourceItem).join('')}</div>` : ''}<div class="viral-source-list">${options.filter(o => !selected.some(s => s.p.id === o.p.id)).slice(0, 30).map(sourceItem).join('') || '<p class="muted">当前筛选没有近期材料。可在 X 信号源刷新或补充材料文字。</p>'}</div><small class="muted">显示最近 30 条匹配材料，可按账号或关键词筛选。</small></details><div class="actions">${b('生成原创参考稿与配图提示词', 'viral-create', '', true)}</div><p class="muted">正文、标题和提示词将用已配置的写作模型生成。保留你的表达，不冒充参考博主，不保证流量。</p></section>${editor}`;
  }
  return `<div class="viral-page">${header}${content}</div>`;
}
