const { createRequire } = require('node:module');
const { spawn } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const bundled = createRequire(path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json'));
const { chromium } = bundled('playwright');
const qa = path.resolve(__dirname, '../../research/qa-x-radar'); fs.mkdirSync(qa, { recursive: true });
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'x-radar-browser-'));
let child, browser;
const pause = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  child = spawn(process.execPath, ['--import', pathToFileURL(path.join(__dirname, 'mock-network.mjs')).href, path.join(__dirname, '../server.mjs')], { env: { ...process.env, XRADAR_DATA: data, XRADAR_PORT: '18771', XRADAR_PUBLIC_PROXY: 'off' }, stdio: 'pipe', windowsHide: true });
  let ready = false;
  for (let i = 0; i < 40; i++) { try { if ((await fetch('http://127.0.0.1:18771/api/health')).ok) { ready = true; break; } } catch {} await pause(200); }
  assert(ready);
  await page.goto('http://127.0.0.1:18771');
  await page.getByRole('heading', { name: '从信息，到值得写的选题。' }).waitFor();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.locator('.nav button[data-view="settings"]').click();
  assert.equal(await page.locator('#imageMode').inputValue(), 'manual');
  assert.equal(await page.locator('#imageKey').isVisible(), false);
  assert.equal(await page.locator('#inputPrice').isVisible(), false);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: path.join(qa, 'manual-settings-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.locator('#textBase').fill('https://example.com/v1');
  await page.locator('#textModel').fill('fixture');
  await page.locator('#textKey').fill('browser-test-key');
  await page.getByRole('button', { name: '保存模型设置', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.locator('#samples').fill('测试代表帖一：具体说明任务。\n\n测试代表帖二：解释限制。\n\n测试代表帖三：给出步骤。');
  await page.getByRole('button', { name: '保存并提炼风格说明', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '确认这份风格说明', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '添加一手来源', exact: true }).click();
  await page.locator('#source-name-0').fill('合成 RSS');
  await page.locator('#source-url-0').fill('https://example.com/feed.xml');
  await page.getByRole('button', { name: '保存信源', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('#source-name-0').inputValue(), '合成 RSS');
  await page.locator('.nav button[data-view="daily"]').click();
  await page.getByRole('button', { name: '生成今日精选', exact: true }).first().click();
  await page.getByRole('heading', { name: '隔离测试选题', exact: true }).waitFor();
  await page.getByRole('button', { name: '选择这个选题 →', exact: true }).click();
  await page.getByRole('button', { name: '确认角度与提纲 →', exact: true }).click();
  await page.locator('#test-notes').fill('这是一份隔离浏览器流程验收记录，不是用户亲测，观察和限制只验证保存流程。');
  await page.getByRole('button', { name: '确认实测结果，进入写作 →', exact: true }).click();
  await page.getByRole('button', { name: '生成正文初稿', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  assert((await page.locator('#draft').inputValue()).length >= 800);
  await page.getByRole('button', { name: '确认正文，准备配图 →', exact: true }).click();
  await page.getByRole('button', { name: '生成配图方案', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.locator('#plan-title-0').fill('修改后的流程测试图');
  await page.locator('#plan-kind-1').selectOption('illustration');
  await page.locator('#plan-prompt-1').fill('用简洁画面说明步骤，不伪造产品截图。');
  await page.getByRole('button', { name: '确认方案，开始制作 →', exact: true }).click();
  await page.getByRole('button', { name: '制作信息图', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:18771' });
  await page.getByRole('button', { name: '复制配图提示词', exact: true }).click();
  assert((await page.evaluate(() => navigator.clipboard.readText())).includes('用简洁画面说明步骤'));
  assert.equal(await page.getByRole('button', { name: '使用图片 API 生成', exact: true }).count(), 0);
  await page.locator('input[type=file]').setInputFiles({ name: '测试像素.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNAAAAABJRU5ErkJggg==', 'base64') });
  await page.getByRole('button', { name: '导入这张插图', exact: true }).click();
  await page.locator('.progressbox').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '图文完成，记录采用 ✓', exact: true }).click();
  await page.getByRole('heading', { name: '图文已准备好。', exact: true }).waitFor();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: path.join(qa, 'workflow-synthetic.png'), fullPage: true });
  await page.reload();
  await page.getByRole('heading', { name: '图文已准备好。', exact: true }).waitFor();
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log(JSON.stringify({ ok: true, browserErrors: errors.length, checks: ['图片 API 与费用默认收起', '390px 窄屏无横向溢出', '模型与风格配置', '选题到正文与配图完整流程（合成服务）', '复制提示词与导入插图，无图片密钥', '刷新恢复'], screenshots: qa }, null, 2));
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(async () => { await browser?.close(); if (child && child.exitCode === null) { child.kill(); await new Promise(r => child.once('exit', r)); } });
