import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'x-radar-acceptance-'));
const port = 18770; const base = `http://127.0.0.1:${port}`;
let child;
const pause = ms => new Promise(r => setTimeout(r, ms));
async function start() { let log = ''; child = spawn(process.execPath, ['--import', pathToFileURL(path.join(here, 'mock-network.mjs')).href, path.join(here, '../server.mjs')], { env: { ...process.env, XRADAR_DATA: data, XRADAR_PORT: String(port), XRADAR_PUBLIC_PROXY: 'off' }, stdio: 'pipe', windowsHide: true }); child.stderr.on('data', c => { log += c.toString(); }); for (let i = 0; i < 60; i++) { try { if ((await fetch(base + '/api/health')).ok) return; } catch {} await pause(200); } throw Error('test server failed: ' + log); }
async function stop() { if (child && child.exitCode === null) { child.kill(); await new Promise(r => child.once('exit', r)); } }
async function request(route, d) { const r = await fetch(base + route, d === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: base }, body: JSON.stringify(d) }); const out = await r.json(); if (!r.ok) throw Error(out.error); return out; }
async function job(route, d) { let j = await request(route, d); for (let i = 0; i < 300 && j.status === 'running'; i++) { await pause(60); j = await request('/api/job/' + j.id); } if (j.status === 'error') throw Error(j.error); assert.equal(j.status, 'done'); return j.result; }
test('full workflow, approval gates, secret redaction, source handling, persistence and local-only access', { timeout: 90000 }, async t => {
  await start(); t.after(stop);
  await assert.rejects(() => job('/api/recommend', {}), /配置/);
  await request('/api/settings', { textBase: 'https://example.com/v1', textModel: 'fixture', textKey: 'secret-test-only', imageMode: 'api', imageBase: 'https://example.com/v1', imageModel: 'fixture-image', imageKey: 'secret-image-test-only', inputPrice: 1, outputPrice: 2, sources: [{ name: '合成 RSS', kind: 'rss', url: 'https://example.com/feed.xml', enabled: true }] });
  const s = await request('/api/state'); assert(!JSON.stringify(s).includes('secret-test-only')); assert.equal(s.settings.hasTextKey, true);
  const daily = await job('/api/recommend', {}); assert.equal(daily.cards.length, 1); assert(daily.reports.some(r => r.name === '合成 RSS' && r.ok && r.count === 1));
  const cached = await job('/api/recommend', {}); assert.equal(cached.id, daily.id);
  let p = await request('/api/project', { cardId: daily.cards[0].id });
  const pd = extra => ({ id: p.id, revision: p.revision, ...extra });
  await assert.rejects(() => job('/api/draft', pd()), /提纲/);
  p = await request('/api/outline', pd({ angle: p.angle, outline: p.outline })); assert.equal(p.stage, 'testing');
  await assert.rejects(() => job('/api/draft', pd()), /实测/);
  p = await job('/api/source', pd({ url: p.card.sources[0].url })); assert(p.evidence.length > 0);
  p = await request('/api/test', pd({ notes: '实际测试记录：此为合成验收，不是真实工具体验。观察结果和限制均不用于生产内容。' }));
  p = await job('/api/draft', pd()); assert(p.draft.length >= 800); assert.equal(p.versions.length, 1);
  p = await job('/api/review', pd()); assert.equal(p.review.summary, '测试审稿摘要'); assert(p.review.issues[0].quote && p.draft.includes(p.review.issues[0].quote));
  await assert.rejects(() => job('/api/plan', pd()), /确认正文/);
  p = await request('/api/draft/approve', pd());
  p = await job('/api/plan', pd());
  await assert.rejects(() => job('/api/image', pd({ planId: p.plan[0].id })), /配图/);
  p = await request('/api/plan/save', pd({ images: [...p.plan, { kind: 'illustration', title: '合成图片接口测试', description: '仅验证接口，不是真实出图', prompt: '测试像素', points: [] }] }));
  p = await request('/api/plan/approve', pd());
  p = await job('/api/image', pd({ planId: p.plan[0].id })); assert.equal(p.assets.length, 1);
  const image = await fetch(base + '/assets/' + p.assets[0].file); assert.equal(image.headers.get('content-type'), 'image/png'); assert((await image.arrayBuffer()).byteLength > 1000);
  await assert.rejects(() => request('/api/complete', pd()), /所有配图/);
  p = await job('/api/image', pd({ planId: p.plan[2].id })); assert(p.assets.some(a => a.kind === 'illustration'));
  p = await request('/api/upload', pd({ planId: p.plan[1].id, label: '合成测试像素.png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNAAAAABJRU5ErkJggg==' }));
  p = await request('/api/complete', pd()); assert.equal(p.stage, 'done');
  const completedId = p.id;
  const revision = p.revision;
  p = await request('/api/draft/save', pd({ body: p.draft + '\n已修改。' })); assert.equal(p.planApproved, false); assert.equal(p.completedAt, null); assert.equal(p.versions.length, 2); assert.equal(p.review, null);
  await assert.rejects(() => request('/api/draft/save', { id: p.id, revision, body: '过期更新' }), /变化|更新/);
  await stop(); await start();
  const restored = await request('/api/state'); assert.equal(restored.projects.find(p => p.id === completedId).versions.length, 2); assert(restored.calls.some(c => c.amount !== null));
  const blocked = await fetch(base + '/api/settings', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://evil.example' }, body: '{}' }); assert.equal(blocked.status, 400);
  await assert.rejects(() => job('/api/material', { url: 'https://127.0.0.1/article', material: '' }), /内部网络/);
  const traversal = await fetch(base + '/assets/not-a-valid-file'); assert.equal(traversal.status, 400);
});

test('manual illustration import needs no image key, preserves approvals, replaces assets and survives restart', { timeout: 30000 }, async t => {
  await start(); t.after(stop);
  await request('/api/settings', { imageMode: 'manual', clearImageKey: true });
  await assert.rejects(() => request('/api/settings', { imageMode: 'invalid' }), /请选择/);
  const initial = await request('/api/state');
  assert.equal(initial.settings.hasImageKey, false);
  let p = await request('/api/project', { cardId: initial.daily.cards[0].id });
  const pd = extra => ({ id: p.id, revision: p.revision, ...extra });
  p = await request('/api/outline', pd({ angle: p.angle, outline: p.outline }));
  p = await request('/api/test', pd({ notes: '这是一份合成测试记录，明确区分实际截图和生成示意图，不用于真实发布。' }));
  p = await request('/api/draft/save', pd({ body: '手动导入流程测试稿。'.repeat(90) }));
  p = await request('/api/draft/approve', pd());
  p = await request('/api/plan/save', pd({ images: [{ kind: 'illustration', title: '网页生成的示意插图', description: '合成导入测试', prompt: '一个清楚的示意画面', points: [] }] }));
  const planId = p.plan[0].id;
  const pixel = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNAAAAABJRU5ErkJggg==';
  await assert.rejects(() => request('/api/upload', pd({ planId, data: pixel })), /确认/);
  p = await request('/api/plan/approve', pd());
  const callsBefore = (await request('/api/state')).calls.length;
  await assert.rejects(() => job('/api/image', pd({ planId })), /网页生成后导入/);
  assert.equal((await request('/api/state')).calls.length, callsBefore);
  await assert.rejects(() => request('/api/upload', pd({ planId, data: 'invalid' })), /PNG/);
  p = await request('/api/upload', pd({ planId, label: 'ChatGPT 示例.png', data: pixel }));
  assert.equal(p.assets[0].kind, 'illustration'); assert.equal(p.assets[0].origin, 'import');
  assert.equal(p.draftApproved, true); assert.equal(p.planApproved, true); assert.equal(p.testApproved, true);
  const oldFile = p.assets[0].file;
  p = await request('/api/upload', pd({ planId, label: '替换后的插图.png', data: pixel }));
  assert.equal(p.assets.filter(a => a.planId === planId).length, 1); assert.notEqual(p.assets[0].file, oldFile);
  p = await request('/api/complete', pd()); assert.equal(p.stage, 'done');
  await stop(); await start();
  const restored = (await request('/api/state')).projects.find(r => r.id === p.id);
  assert.equal(restored.stage, 'done'); assert.equal(restored.assets[0].kind, 'illustration');
  const image = await fetch(base + '/assets/' + restored.assets[0].file); assert.equal(image.status, 200);
});

test('image connection test persists a separate preview, diagnoses group permissions and never exposes provider credentials', { timeout: 30000 }, async t => {
  await start(); t.after(stop);
  const originalProjects = (await request('/api/state')).projects;
  await request('/api/settings', { imageMode: 'api', imageBase: 'https://example.com/v1', imageModel: 'fixture-image', imageKey: 'secret-image-test-only' });
  const result = await job('/api/image/test', {});
  assert.equal(result.ok, true);
  let state = await request('/api/state');
  assert.equal(state.settings.imageCheck.status, 'ready');
  assert.equal(state.settings.imageCheck.previewFile, result.file);
  assert.deepEqual(state.projects, originalProjects, 'Testing image credentials must not approve or alter drafts');
  const preview = await fetch(base + '/assets/' + result.file);
  assert.equal(preview.headers.get('content-type'), 'image/png'); assert((await preview.arrayBuffer()).byteLength > 0);
  await stop(); await start();
  assert.equal((await request('/api/state')).settings.imageCheck.previewFile, result.file);
  await request('/api/settings', { imagePrice: '' });
  assert.equal((await request('/api/state')).settings.imageCheck.status, 'ready');
  await request('/api/settings', { imageModel: 'blocked-image' });
  assert.equal((await request('/api/state')).settings.imageCheck, null);
  await assert.rejects(() => job('/api/image/test', {}), /当前密钥所属分组未开启图片生成/);
  state = await request('/api/state');
  assert.equal(state.settings.imageCheck.status, 'failed');
  assert.equal(state.settings.imageCheck.code, 'image_group_disabled');
  assert.equal(state.settings.imageCheck.previewFile, undefined);
  assert(state.calls.some(c => c.purpose === '图片连接测试' && c.status === 'failed_or_invalid'));
  assert(!JSON.stringify(state).includes('secret-image-test-only'));
  await request('/api/settings', { imageModel: 'invalid-error-image' });
  await assert.rejects(() => job('/api/image/test', {}), /图片服务返回 400/);
  assert(!JSON.stringify(await request('/api/state')).includes('private provider error'));
  await request('/api/settings', { imageKey: 'replacement-image-test-only' });
  assert.equal((await request('/api/state')).settings.imageCheck, null);
});
